[font]

# Normal font style
# normal = { family = "monospace", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular
normal = { family = "VL Gothic", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular
# family = "VL PGothic"
# style = "Regular"

# Font size in points
size = 10.25

# Offset is extra space around each character
offset = { x = 1, y = 0 }  # Default: x = 0, y = 0


# 縮小を無効化
[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "None"
