[font]

# Normal font style
# normal = { family = "monospace", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular
normal = { family = "VL Gothic", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular
# family = "VL PGothic"
# style = "Regular"

# Offset is extra space around each character
offset = { x = 1, y = 0 }  # Default: x = 0, y = 0

# Font size in points
# size = 10.25
# ====== Thinkpad用設定 ======
size = 7.25

[colors.normal]
black = "#000000"
red = "#ff0000"
green = "#00ff00"
yellow = "#ffff00"
blue = "#0000ff"
magenta = "#ff00ff"
cyan = "#1fbdd2"
white = "#ffffff"

[colors.bright]
black = "#000000"
red = "#ff0000"
green = "#00ff00"
yellow = "#ffff00"
blue = "#0000ff"
magenta = "#ff00ff"
cyan = "#00ffff"
white = "#ffffff"

[colors.primary]
background = "#000000"
# ====== Thinkpad用設定ここまで ======

# 縮小を無効化
[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "None"
